# Generated by Django 5.1.2 on 2024-10-27 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_gallery_created_at'),
    ]

    operations = [
    ]
