# Generated by Django 5.1.2 on 2024-10-28 11:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_auto_20241027_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='gallery_covers/'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
