# Generated by Django 5.1.2 on 2024-11-30 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0009_alter_image_options_remove_gallery_updated_at_and_more'),
    ]

    operations = [
    ]
