# Generated by Django 5.1.2 on 2024-11-30 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0010_fix_gallery_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-created_at'], 'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
    ]
