# Generated by Django 5.1.2 on 2024-10-26 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_gallery_galleryimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryimage',
            name='gallery',
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
        migrations.DeleteModel(
            name='GalleryImage',
        ),
    ]
