# Generated by Django 5.1.2 on 2024-11-30 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_blogcategory_options_blogcategory_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcategory',
            name='description',
        ),
    ]
