# Generated by Django 5.1.2 on 2024-11-30 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_remove_blogcategory_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='blog_category',
        ),
        migrations.RemoveField(
            model_name='image',
            name='blog_category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.DeleteModel(
            name='BlogCategory',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
