# Generated by Django 5.1.2 on 2024-10-23 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
