# Generated by Django 5.1.2 on 2024-10-27 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
